routes/web.php
<?php

use App\Http\Controllers\KlinikController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\SuratController;
use App\Http\Controllers\RekamController;
use App\Http\Controllers\DetailController;
use Illuminate\Support\Facades\Route;

Route::get("/", function (){
   return redirect()->route('login');
});
Auth::routes();

Route::get('/klinik', [KlinikController::class, 'klinik'])->name('klinik');

Route::resource('klinik',KlinikController::class);

Route::resource('pegawai',PegawaiController::class);

Route::resource('surat',SuratController::class);

Route::resource('rekam',RekamController::class);
Route::resource('detail',DetailController::class);

Route::resource('/obat', ObatController::class);

Route::post('/viewDetail', [DetailController::class, 'viewDetail'])->name('viewDetail');
Route::get('/viewDetail', [DetailController::class, 'viewDetail'])->name('viewDetail');

app/Models/Klinik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Klinik extends Model
{
    use HasFactory;
    use Sortable;
    protected $table = 'Klinik';
    protected $guarded = ['id'];

    public $sortable = [
        'nama', 'tgllahir',
    ];

    protected $fillable = [
        'nama',
        'nik',
        'tgllahir',
        'telepon',
    ];
}

app/Http/Controllers/KlinikController.php
<?php

namespace App\Http\Controllers;

use App\Models\Klinik;
use Illuminate\Http\Request;

class KlinikController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $cari = $request->query('cari');
        if(!empty($cari)){
            $klinik = Klinik::sortable()
            ->where('klinik.nama', 'like','%'.$cari.'%')
            ->orWhere('klinik.nik', 'like','%'.$cari.'%')
            ->paginate(5)->onEachSide(2)->fragment('klinik');
        }else{
            $klinik = Klinik::sortable()->paginate(5)->onEachSide(2)->fragment('klinik');
        }


        return view('klinik.index')->with([
            'klinik' => $klinik,
            'cari' => $cari,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('klinik.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|min:1',
            'nik' => 'required|min:1',
            'tgllahir' => 'required|min:1',
            'telepon' => 'required|min:1',
        ]);

        $klinik = new Klinik();
        $klinik->nama = $request->nama;
        $klinik->nik = $request->nik;
        $klinik->tgllahir = $request->tgllahir;
        $klinik->telepon = $request->telepon;
        $klinik->save();

        return to_route('klinik.index')->with('success', 'Data Berhasil di Tambah.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('klinik.edit')->with([
            'klinik' => Klinik::find($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required|min:1',
            'nik' => 'required|min:1',
            'tgllahir' => 'required|min:1',
            'telepon' => 'required|min:1',
        ]);

        $klinik = Klinik::find($id);
        $klinik->nama = $request->nama;
        $klinik->nik = $request->nik;
        $klinik->tgllahir = $request->tgllahir;
        $klinik->telepon = $request->telepon;
        $klinik->save();

        return to_route('klinik.index')->with('success', 'Data Berhasil di Edit.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $klinik = Klinik::find($id);
        $klinik->delete();

        return back()->with('success', 'Data berhasil di Hapus.');
    }
}

resources/views/klinik/edit.blade.php
@extends('layouts.pages')

@section('content')

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route("klinik.index")}}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{route("klinik.index")}}">Data Pasien</a></li>
                        <li class="breadcrumb-item active">Edit Data Pasien</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="container">
            <h4 class="text-center">Form Edit Data Pasien</h4>
            <a href="{{ route('klinik.index') }}" class="btn btn-primary mb-3">Data Pasien</a>
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('klinik.update', $klinik->id) }}" method="POST">
                        @csrf
                        @method('patch')
                        <div>
                            <label for="nama" class="form-label">Nama</label>
                            <input type="text" class="form-control" name="nama"
                                   value="{{ $klinik->nama }}" id="nama">
                        </div>
                        <div>
                            <label for="nik" class="form-label">NIK</label>
                            <input type="text" class="form-control" name="nik"
                                   value="{{ $klinik->nik }}" id="nik">
                        </div>
                        <div>
                            <label for="tgllahir" class="form-label">Tanggal Lahir</label>
                            <input type="text" class="form-control" name="tgllahir"
                                   value="{{ $klinik->tgllahir }}" id="tgllahir">
                        </div>
                        <div>
                            <label for="telepon" class="form-label">Telepon</label>
                            <input type="text" class="form-control" name="telepon"
                                   value="{{ $klinik->telepon }}" id="Keluhan">
                        </div>
                        <button type="submit" class="btn btn-primary float-right">Edit</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->

@endsection

resources/views/klinik/index.blade.php
@extends('layouts.pages')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route("klinik.index")}}">Home</a></li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="container">
            <h2 class="text-center">Pendaftaran Pasien</h2>
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('klinik.store') }}" method="POST">
                        @csrf
                        <div class="mb-3 row">
                            <label for="nama" class="col-sm-2 col-form-label ml-5">Nama</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="nama" id="nama">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="nik" class="col-sm-2 col-form-label ml-5">NIK</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="nik" id="nik">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="tgllahir" class="col-sm-2 col-form-label ml-5">Tanggal Lahir</label>
                            <div class="col-sm-7">
                                <input type="date" class="form-control" name="tgllahir" id="tgllahir">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="telepon" class="col-sm-2 col-form-label ml-5">Telepon</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="telepon" id="telepon">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary float-right mr-5">Daftar</button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Default box -->
        <div class="container">
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif
            <div class="card">
                <div class="card-body">
                    <table class="table table-striped">
                        <form method="GET">
                            <div class="form-group row text-right ml-5">
                                <label class="col-sm-11 ml-5">
                                    <input type="text" name="cari" class="from-control" style="background-color:#D1E0E0;"
                                           placeholder="Cari Nama atau NIK" autofocus="true" value={{ $cari }}>
                                </label>
                            </div>
                        </form>
                        <thead>
                        <th>Nomor</th>
                        <th>@sortablelink('nama', 'Nama')</th>
                        <th>NIK</th>
                        <th>@sortablelink('tgllahir', 'Tanggal Lahir')</th>
                        <th>Telepon</th>
                        <th></th>
                        </thead>
                        <tbody>
                        @php
                            $nomor = 1 + (($klinik->currentPage()-1)* $klinik->perPage());
                        @endphp
                        @if ($klinik->count() > 0)
                            @foreach ($klinik as $hasil)
                                <tr>
                                    <th>{{ $nomor++ }}</th>
                                    <td>{{ $hasil->nama }}</td>
                                    <td>{{ $hasil->nik }}</td>
                                    <td>{{ date('j F Y', strtotime($hasil->tgllahir)) }}</td>
                                    <td>{{ $hasil->telepon }}</td>
                                    <td>
                                        <form action="{{ route('klinik.destroy', $hasil->id) }}"
                                              method="POST">
                                            @csrf
                                            @method('delete')
                                            <a href="{{ route('klinik.edit', $hasil->id) }}"
                                               class="btn btn-success btn-sm">Edit</a>
                                            <button class="btn btn-danger btn-sm">Hapus</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="10" class="text-center">Tidak ada Data!</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
                <div style="margin: 25px;
                        width: 350px;">
                    {{-- {{ $klinik->links() }} --}}
                    {!! $klinik->appends(Request::except('page'))->render() !!}
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@endsection