routes/web.php
<?php

use App\Http\Controllers\KlinikController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\SuratController;
use App\Http\Controllers\RekamController;
use App\Http\Controllers\DetailController;
use Illuminate\Support\Facades\Route;

Route::get("/", function (){
   return redirect()->route('login');
});
Auth::routes();

Route::get('/klinik', [KlinikController::class, 'klinik'])->name('klinik');

Route::resource('klinik',KlinikController::class);

Route::resource('pegawai',PegawaiController::class);

Route::resource('surat',SuratController::class);

Route::resource('rekam',RekamController::class);
Route::resource('detail',DetailController::class);

Route::resource('/obat', ObatController::class);

Route::post('/viewDetail', [DetailController::class, 'viewDetail'])->name('viewDetail');
Route::get('/viewDetail', [DetailController::class, 'viewDetail'])->name('viewDetail');

app/Models/Pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    use HasFactory;
    protected $table = 'Pegawai';
    protected $guarded = ['id'];
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pegawai;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pegawai.index')->with([
            'pegawai' => Pegawai::paginate(6),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pegawai.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'propesi' => 'required|min:1',
            'nama' => 'required|min:1',
            'alamat' => 'required|min:1|max:20',
            'telepon' => 'required|min:1',
            'hari' => 'required|min:1',
            'jam' => 'required|min:1',
            'foto' => 'required|image|mimes:png,jpg,jpeg|max:2048',
        ]);

        //mengambil data foto yang diupload
        $foto           = $request->foto;
        //mengambil nama foto
        $slug      = Str::slug($foto->getClientOriginalName());
        $new_foto = time() .'_'. $slug;
        $foto->move('uploads/klinik/', $new_foto);

        $pegawai = new Pegawai();
        $pegawai->propesi = $request->propesi;
        $pegawai->nama = $request->nama;
        $pegawai->alamat = $request->alamat;
        $pegawai->telepon = $request->telepon;
        $pegawai->hari = $request->hari;
        $pegawai->jam = $request->jam;
        $pegawai->foto = 'uploads/klinik/'. $new_foto;
        $pegawai->save();

        return to_route('pegawai.index')->with('success', 'Data Berhasil di Tambah.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pegawai/create.blade.php
@extends('layouts.pages')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route("klinik.index")}}">Home</a></li>
                        <li class="breadcrumb-item"><a href="/klinikdel/public/pegawai">Data Pegawai</a></li>
                        <li class="breadcrumb-item active">Tambah Data Pegawai</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="container">
            <h2 class="text-center">Form Tambah Data Pegawai</h2>
            <a href="{{ route('pegawai.index') }}" class="btn btn-primary mb-2">Data Pegawai</a>
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('pegawai.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3 row">
                            <label for="propesi" class="col-sm-2 col-form-label">Profesi</label>
                            <div class="col-sm-2">
                                <select class="form-select form-control" name="propesi" id="propesi">
                                    <option value="Dokter">Dokter</option>
                                    <option value="Perawat">Perawat</option>
                                    <option value="Bidan">Bidan</option>
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="nama" id="nama">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="alamat" id="alamat">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="telepon" class="col-sm-2 col-form-label">Telepon</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="telepon" id="telepon">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="hari" class="col-sm-2 col-form-label">Hari Kerja</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" name="hari" id="hari">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="jam" class="col-sm-2 col-form-label">Jam Kerja</label>
                            <div class="col-sm-7">
                                <input type="time" class="form-control" name="jam" id="jam">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="foto" class="col-sm-2 col-form-label">Upload Foto</label>
                            <div class="col-sm-7">
                                <input type="file" name="foto" id="foto" accept="image/*"
                                       onchange="document.getElementById('output').src = window.URL.createObjectURL(this.files[0])">
                            </div>
                        </div>
                        <div class="ml-5"><img src="" id="output" width="150px"></div>
                        <button type="submit" class="btn btn-primary float-right">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
@endsection

resources/views/pegawai/index.blade.php
@extends('layouts.pages')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="{{route("klinik.index")}}">Home</a></li>
                        <li class="breadcrumb-item active">Data Pegawai</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="container">
            <h2 class="text-center">Data Pegawai</h2>
            <a href="{{ route('pegawai.create') }}" class="btn btn-primary mb-3">Tambah Data</a>
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row">
                        <table class="table table-striped">
                            </tbody>
                            @if ($pegawai->count() > 0)
                                @foreach ($pegawai as $hasil)
                                    <tr>
                                        <div
                                            class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
                                            <div class="card bg-light d-flex flex-fill">
                                                <div class="card-header text-muted border-bottom-0">
                                                    {{ $hasil->propesi }}
                                                </div>
                                                <div class="card-body pt-0">
                                                    <div class="row">
                                                        <div class="col-7">
                                                            <h2 class="lead"><b>{{ $hasil->nama }}</b></h2>
                                                            <ul class="ml-4 mb-4 fa-ul text-muted">
                                                                <li class="small"><span class="fa-li"><i
                                                                            class="fas fa-lg fa-building"></i></span>
                                                                    Alamat:
                                                                    {{ $hasil->alamat }}</li>
                                                                <li class="small"><span class="fa-li"><i
                                                                            class="fas fa-lg fa-phone"></i></span>
                                                                    Telepon :
                                                                    {{ $hasil->telepon }}
                                                                </li>
                                                            </ul>
                                                            <p class="text-muted text-sm"><b>Hari Kerja: </b>
                                                                {{ $hasil->hari }} <br> <b>Jam Kerja: </b>
                                                                {{ $hasil->jam }}</p>
                                                        </div>
                                                        <div class="col-5 text-center">
                                                            <img src="{{ asset( $hasil->foto )}}"
                                                                 alt="user-avatar"
                                                                 class="img-circle img-fluid" height="100px">
                                                        </div>
                                                    </div>
                                                </div>
                                                {{-- <div class="card-footer">
                                                    <div class="text-right">
                                                        <a href="#" class="btn btn-sm btn-primary">
                                                            <i class="fas fa-user"></i> View Profile
                                                        </a>
                                                    </div>
                                                </div> --}}
                                            </div>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="10" class="text-center">Tidak ada Data!</td>
                                </tr>
                        @endif
                    </div>
                    </tbody>
                    </table>
                </div>
                <div style="margin: 25px;
                        width: 350px;">
                    {{ $pegawai->links() }}
                </div>
            </div>
            <!-- /.card-body -->
        </div>
        </div>
        <!-- /.card -->
@endsection